const busSeatData = [
    { id: 'B1', status: 'booked', price: 0 },
    { id: 'B3', status: 'booked', price: 0 },
    { id: 'B5', status: 'booked', price: 0 },
    { id: 'B7', status: 'booked', price: 0 },
    { id: 'B9', status: 'booked', price: 0 },
    { id: 'B11', status: 'booked', price: 0 },
    { id: 'B13', status: 'booked', price: 0 },
    { id: 'B15', status: 'booked', price: 0 },
    { id: 'B17', status: 'booked', price: 0 },

    { id: 'B2', status: 'booked', price: 0 },
    { id: 'B4', status: 'booked', price: 0 },
    { id: 'B6', status: 'booked', price: 0 },
    { id: 'B8', status: 'booked', price: 0 },
    { id: 'B10', status: 'booked', price: 0 },
    { id: 'B12', status: 'booked', price: 0 },
    { id: 'B14', status: 'booked', price: 0 },
    { id: 'B16', status: 'booked', price: 0 },
    { id: 'B18', status: 'booked', price: 0 },

    { id: '19', status: 'booked', price: 0 },

    { id: 'A1', status: 'booked', price: 0 },
    { id: 'A3', status: 'booked', price: 0 },
    { id: 'A5', status: 'booked', price: 0 },
    { id: 'A7', status: 'booked', price: 0 },
    { id: 'A9', status: 'booked', price: 0 },
    { id: 'A11', status: 'booked', price: 0 },
    { id: 'A13', status: 'booked', price: 0 },
    { id: 'A15', status: 'booked', price: 0 },
    { id: 'A17', status: 'booked', price: 0 },

    { id: 'A2', status: 'booked', price: 0 },
    { id: 'A4', status: 'booked', price: 0 },
    { id: 'A6', status: 'booked', price: 0 },
    { id: 'A8', status: 'booked', price: 0 },
    { id: 'A10', status: 'booked', price: 0 },
    { id: 'A12', status: 'booked', price: 0 },
    { id: 'A14', status: 'booked', price: 0 },
    { id: 'A16', status: 'booked', price: 0 },
    { id: 'A18', status: 'booked', price: 0 },
]

export default busSeatData;